name: DynamicPatches
main: prokits\Patches
version: 2.0.0
api: 5.0.0
author: Misaka
load: STARTUP
commands:
  loadPatch:
    description: 'load Patch'
    usage: '/loadPatch <Patch Name>'
    permission: dynamicpatches.load
permissions:
  dynamicpatches.load:
    description: "load patch"
    default: true